version: '3.7'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 940220
    volumes:
      - ./data/postgres:/var/lib/postgresql